config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#top'
  get "home/about" => "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  resources :users, only:[:index, :show, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to books_path
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <%= render "layouts/message", {text: @book} %>
  <h1>Editing Book</h1>
  <div class="row">
    <div class="col-xs-12 form-box">
      <%= form_for (@book) do |f| %>
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title, autofocus: true %>
        </div>

        <div class="field">
          <%= f.label :opinion %><br>
          <%= f.text_area :body %>
        </div>

        <div class="button">
          <%= f.submit "Update Book", class:"btn btn-primary" %>
        </div>

      <% end %>
      <div class="menu">
        <p><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render "layouts/message", {text: @book} %>
  <div class="row">
    <div class="col-xs-3">
      <%= render "layouts/info", {user: @user, book: @book} %>
    </div>
    <div class="col-xs-9">
      <h2 class="sub-title">Books</h2>
      <% if @books.blank? %>
        <p class="none">投稿がまだありません</p>
      <% else %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th colspan="1"></th>
              <th class="content-title">Title</th>
              <th class="content-opinion">Opinion</th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td class="user-profile-image">
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:"50x50" %>
                <% end %>
              </td>
              <td class="content-title"><%= link_to  book.title, book_path(book) %></td>
              <td class="content-opinion"><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <%= render "layouts/message", {text: @book} %>
  <div class="row">
    <div class="col-xs-3">
      <%= render "layouts/info", {user: @user, book: Book.new} %>
    </div>
    <div class="col-xs-9">
      <h2 class="sub-title">Book detail</h2>
        <table class="table table-striped">
          <tbody>
            <% if @book.user_id != current_user.id %>
              <tr>
                <td class="user-profile-image">
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:"50x50" %><br>
                    <p><%= @user.name %></p>
                  <% end %>
                </td>
                <td class="content-title"><%=@book.title %></td>
                <td class="content-opinion"><%= @book.body %></td>
              </tr>
            <% else %>
              <tr>
                <td class="user-profile-image" style="width:10%">
                  <%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:"50x50" %><br>
                    <p><%= @user.name %></p>
                  <% end %>
                </td>
                <td class="content-title" style="width:20%"><%=@book.title %></td>
                <td class="content-opinion" style="width:40%"><%= @book.body %></td>
                <td class="buttons" style="width:30%">
                  <div class="btn btn-success edit">
                    <%= link_to "Edit", edit_book_path(@book) %>
                  </div>
                  <div class="btn btn-danger delete">
                    <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>

        </table>
    </div>
  </div>
</div>