config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#top'
  get "home/about" => "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  resources :users, only:[:index, :show, :edit, :update]
end

app/views/layouts/_info.html.erb
<div class="infomation-box">
  <h2 class="sub-title">User info</h2>
  <div class="profile-image">
    <%= attachment_image_tag user, :profile_image, :fill, 150,150, fallback: "no_image.jpg", size:"150x150" %>
  </div>
  <table class="table">
    <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
</div>
<div class="row">
  <%= link_to edit_user_path(current_user.id) do %>
    <span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user"></span>
  <% end %>
</div>
<div class="form-box">
  <h3 class="sub-title">New book</h3>
  <%= form_for (book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <div class="button">
      <%= f.submit "Create Book", class:"btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/layouts/_message.html.erb
<div class="messages row">
  <% if text.errors.any? %>
    <div class="error-box">
      <div class="error-text">
        <% if text == @user %>
          <%= text.errors.count %>errors prohibited this user from being saved:
        <% else %>
          <%= text.errors.count %>errors prohibited this book from being saved:
        <% end %>
      </div>
      <ul class="errors">
        <% text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="success">
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="navbar navbar-inverse navbar-fixed-top clearfix">
      <div class="container">
        <div class="row">
          <nav class="nav navbar-nav navbar-left">
            <h2 class="title">Bookers</h2>
          </nav>
          <nav>
            <% if user_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to user_path(current_user) do %>
                    <span class="glyphicon glyphicon-home home">  Home</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path do %>
                    <span class="glyphicon glyphicon-user users">  Users</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path do %>
                    <span class="glyphicon glyphicon-book books">  Books</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to "/users/sign_out", method: :delete do %>
                    <span class="glyphicon glyphicon-log-out logout">  logout</span>
                  <% end %>
                </li>
              </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to root_path do %>
                    <span class="glyphicon glyphicon-home home">  Home</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path do %>
                    <span class="glyphicon glyphicon-link about">  About</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path do %>
                    <span class="glyphicon glyphicon-edit sign_up">  sign Up</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path do %>
                    <span class="glyphicon glyphicon-log-in sign_in">  login</span>
                  <% end %>
                </li>
              </ul>
            <% end %>
          </nav>
        </div>
      </div>
    </header>
    <main class="row">
      <%= yield %>
    </main>
    <div class="row">
      <div class="copy col-xs-offset-8 col-xs-4">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </body>
</html>